# Generated by Django 2.0.5 on 2018-06-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('comment', models.CharField(max_length=128, verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('capacity', models.SmallIntegerField(verbose_name='Capacity')),
                ('avalibility', models.BooleanField(default=True, verbose_name='Avalibility')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Room', verbose_name='Rooms'),
        ),
    ]
