# Generated by Django 2.0.5 on 2018-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='avalibility',
        ),
        migrations.AddField(
            model_name='room',
            name='projector_availability',
            field=models.BooleanField(default=True, verbose_name='Projector availability'),
        ),
    ]
